CeylonClassLoader causing NoClassDefFoundError
When doing ClassLoader magic like I do in `ceylon.build` (file `ceylon/build/tasks/GatewayClassLoader.java`) the anonymous `Enumeration` class distorts the classloader for the Ant wrapper in ceylon.build.

This pull request enables ceylon.build calling Ant calling ceylon-plugin of ceylon-ant.jar

Otherwise the following error occurs:
```
ceylon.build.tasks.ant.AntBuildException "Error running Ceylon plugin tool (an exception was thrown, run ant with -v parameter to see the exception)"
        at ceylon.build.tasks.ant.Gateway.buildAntException$priv$(Gateway.ceylon:59)
        at ceylon.build.tasks.ant.Gateway.invoke$canonical$(Gateway.ceylon:96)
        at ceylon.build.tasks.ant.Gateway.invoke(Gateway.ceylon:88)
        at ceylon.build.tasks.ant.AntProject.execute$canonical$(AntProject.ceylon:91)
        at ceylon.build.tasks.ant.AntProject.execute(AntProject.ceylon:86)
        at build.scripts_.scripts(build.ceylon:243)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.$call$(AppliedFunction.java:251)
        at com.redhat.ceylon.compiler.java.Util.apply(Util.java:1371)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.apply(Metamodel.java:1646)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:403)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:394)
        at ceylon.build.runner.functionModelToFunction_$1.$call$(goal-annotations.ceylon:87)
        at ceylon.build.engine.executeTask_.executeTask(execution.ceylon:66)
        at ceylon.build.engine.executeGoal_.executeGoal(execution.ceylon:57)
        at ceylon.build.engine.runGoals_.runGoals(execution.ceylon:32)
        at ceylon.build.engine.processGoals_.processGoals(build.ceylon:43)
        at ceylon.build.engine.runEngine_.runEngine(build.ceylon:16)
        at ceylon.build.runner.start_.start(run.ceylon:45)
        at ceylon.build.runner.run_.run(run.ceylon:27)
        at ceylon.build.runner.run_.main(run.ceylon)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
        at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
        at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
        at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
        at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
        at ceylon.modules.Main.execute(Main.java:69)
        at ceylon.modules.Main.main(Main.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.modules.Module.run(Module.java:312)
        at org.jboss.modules.Main.main(Main.java:460)
        at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
        at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
        at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
Caused by: ceylon.build.tasks.ant.sealed.SealedAntBuildException: Error running Ceylon plugin tool (an exception was thrown, run ant with -v parameter to see th
e exception)
        at ceylon.build.tasks.ant.sealed.SealedAnt.execute(SealedAnt.java:146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at ceylon.build.tasks.ant.GatewayCaller.invoke(GatewayCaller.java:65)
        at ceylon.build.tasks.ant.Gateway.invoke$canonical$(Gateway.ceylon:94)
        ... 51 more
Caused by: Error running Ceylon plugin tool (an exception was thrown, run ant with -v parameter to see the exception)
        at com.redhat.ceylon.ant.CeylonAntTask.executeCommandline(CeylonAntTask.java:228)
        at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAntTask.java:173)
        at ceylon.build.tasks.ant.sealed.SealedAnt.execute(SealedAnt.java:144)
        ... 57 more
Caused by: java.lang.NoClassDefFoundError: com/redhat/ceylon/launcher/CeylonClassLoader$1
        at com.redhat.ceylon.launcher.CeylonClassLoader.getResources(CeylonClassLoader.java:225)
        at com.redhat.ceylon.common.tool.ServiceToolLoader.getServiceMeta(ServiceToolLoader.java:36)
        at com.redhat.ceylon.common.tool.ServiceToolLoader.toolClassNames(ServiceToolLoader.java:71)
        at com.redhat.ceylon.common.tool.ToolLoader.getToolClassName(ToolLoader.java:60)
        at com.redhat.ceylon.common.tools.CeylonToolLoader.getToolClassName(CeylonToolLoader.java:40)
        at com.redhat.ceylon.common.tool.ToolLoader.loadToolModelMemoised(ToolLoader.java:110)
        at com.redhat.ceylon.common.tool.ToolLoader.loadToolModel(ToolLoader.java:103)
        at com.redhat.ceylon.common.tools.CeylonTool.getToolModel(CeylonTool.java:488)
        at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:323)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
        at com.redhat.ceylon.ant.CeylonAntTask.executeCommandline(CeylonAntTask.java:216)
        ... 59 more
```