Util.hasError: ignore UsageWarnings and fail fast with an exception
That's a lot faster than walking the whole tree on error. One day we should count
how many times we walk the tree for nothing, because when there is no error we don't
cache the info, so we could potentially walk the tree X times if we wonder X times
if there's an error or not.
Must ignore UsageWarnings otherwise real errors were not added in methods that
where private and never used. Or methods that contained QuotedLiterals.